set -g @plugin 'christoomey/vim-tmux-navigator'

set -g default-terminal "screen-256color"

source-file '/Users/adamkowalski/.tmux/gruvbox'

unbind C-b
set-option -g prefix C-a

bind s split-window -v
bind v split-window -h

run '~/.tmux/plugins/tpm/tpm'
