set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "arcticicestudio/nord-tmux"

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set-option -g prefix C-a

bind s split-window -v
bind v split-window -h

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
