local keymap = vim.keymap
keymap.set("n", "<c-j>", ":wincmd j<CR>")
keymap.set("n", "<c-k>", ":wincmd k<CR>")
keymap.set("n", "<c-h>", ":wincmd h<CR>")
keymap.set("n", "<c-l>", ":wincmd l<CR>")
keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Definition" })
keymap.del("n", "grr")
keymap.del("n", "gra")
keymap.del("n", "grn")
keymap.del("n", "gri")
keymap.del("n", "grt")
keymap.set("n", "gr", vim.lsp.buf.references, { desc = "References" })
keymap.set("n", "gR", vim.lsp.buf.rename, { desc = "Rename" })
keymap.set("n", "ga", vim.lsp.buf.code_action, { desc = "Code action" })
