local o = vim.opt
local g = vim.g
o.tabstop = 2
o.shiftwidth = 2
o.softtabstop = 2
o.expandtab = true
o.autoread = true
o.cmdheight = 0
o.signcolumn = "yes"
o.backspace = "indent,eol,start"
o.winborder = "rounded"
o.number = true
o.mousescroll = "ver:1,hor:6"
o.relativenumber = true
o.cursorline = true
o.termguicolors = true
o.smartindent = true
o.autoindent = true
o.list = true
o.clipboard = "unnamedplus"
o.ignorecase = true
o.smartcase = true
o.hlsearch = true
o.incsearch = true
o.scrolloff = 10
o.sidescrolloff = 8
o.backup = false
o.writebackup = false
o.swapfile = false
o.errorbells = false
g.mapleader = " "
