require('config.options')
require('plugins.clue')
require('plugins.diff')
require('plugins.files')
require('plugins.git')
require('plugins.pairs')
require('plugins.rainbow-delimiters')
require('plugins.tokyonight')
