require('config.keymaps')
require('config.lsp')
require('config.options')

require('plugins.animate')
require('plugins.catppuccin')
require('plugins.clue')
require('plugins.diff')
require('plugins.files')
require('plugins.git')
require('plugins.icons')
require('plugins.indentscope')
require('plugins.pairs')
require('plugins.pick')
require('plugins.rainbow-delimiters')
require('plugins.statusline')
