vim.pack.add({'https://github.com/nvim-mini/mini-git.git'})
require('mini.git').setup()
vim.keymap.set('n', '<leader>gs', ':Git status<cr>', { desc = 'Git status' })
vim.keymap.set('n', '<leader>ga', ':Git add .<cr>', { desc = 'Git add' })
vim.keymap.set('n', '<leader>gc', ':Git commit<cr>', { desc = 'Git commit' })
vim.keymap.set('n', '<leader>gl', ':Git log<cr>', { desc = 'Git log' })
